//
// String table
//
// Note that the Unicode versions use %ls vs. %s, other than that they are identical.
//

#ifndef SPANISH

#ifdef UNICODE

// Verification file errors
#define IDS_SETTRANSFAILED				_T("SetTransaction Failed")
#define IDS_INVALIDLOCATION				_T("Invalid location: %ls")
#define IDS_INVALIDMNU					_T("Invalid MNU: %ls")
#define IDS_INVALIDCHARTYPE				_T("%ls, invalid char type: %ls")
#define IDS_INVALIDFIELDSIZE			_T("%ls, invalid field size: %ls")
#define IDS_INVALIDOCCURRENCES			_T("%ls, invalid occurrence value: %ls")
#define IDS_INVALIDDESCRIPTION			_T("%ls, invalid description value: %ls")
#define IDS_INVALIDLONGDESCRIPTION		_T("%ls, invalid long description value: %ls")
#define IDS_INVALIDSCA					_T("%ls, invalid sca value: %ls")
#define IDS_INVALIDDATEFORMAT			_T("%ls, invalid date format value: %ls")
#define IDS_INVALIDADVANCEDRULE			_T("%ls, invalid advanced rule: %ls")
#define IDS_INVALIDMMAP					_T("%ls, invalid mmap value: %ls")
#define IDS_INVALIDOMAP					_T("%ls, invalid omap value: %ls")
// NIST file validation errors
#define IDS_EXCEPTIONUNK        		_T("[%ls] Unknown exception occurred.")
#define IDS_TOTRECORDSMAX       		_T("Transaction Type %ls may contain at most %ld Type %ld records: it contains %ld")
#define IDS_TOTRECORDSMIN       		_T("Transaction Type %ls must contain at least %ld Type %ld records: it only contains %ld.")
#define IDS_TOTRECORDUNSUPPORTED 		_T("Transaction Type %ls may not contain Type %ld records: it contains %ld of them.")
#define IDS_MANDATORYFIELD      		_T("Mandatory field not present")
#define IDS_UNSUPPORTEDFIELD    		_T("Unsupported field present")
#define IDS_VERTOTUNK           		_T("Verification file does not contain Transaction Type %ls")
#define IDS_NOTOTFIELD          		_T("Failed to find TOT field in Record 1")
#define IDS_INCORRECTITEMCOUNT  		_T("Incorrect item count (%ld), must be 1")
#define IDS_INVALIDLENGTH       		_T("Invalid length of %ld, should be %ld")
#define IDS_INVALIDLENGTHMIN    		_T("Invalid length of %ld, minimum allowed is %ld")
#define IDS_INVALIDLENGTHMAX    		_T("Invalid length of %ld, maximum allowed is %ld")
#define IDS_INVALIDTOTALLENGTH  		_T("Invalid total subfield length of %ld, should be %ld")
#define IDS_INVALIDTOTALLENGTHMIN  		_T("Invalid total subfield length of %ld, minimum allowed is %ld")
#define IDS_INVALIDTOTALLENGTHMAX		_T("Invalid total subfield length of %ld, maximum allowed is %ld")
#define IDS_CHARINVALIDVALUE    		_T("Invalid value '%ls' for CharType '%ls'")
#define IDS_CHARINVALIDVALUESPECIAL		_T("Invalid value '%ls' for CharType '%ls', Special Chars '%ls'")
#define IDS_TOOMANYDATACHARS    		_T("Invalid value %ld for CharType '%ls'")
#define IDS_INVALIDYEAR         		_T("Invalid year %ld")
#define IDS_INVALIDMONTH        		_T("Invalid month %ld")
#define IDS_INVALIDDAY          		_T("Invalid day %ld")
#define IDS_INVALIDMMAPDATA				_T("'%ls': invalid data from mandatory map")
#define IDS_TOOFEWSUBFIELDS     		_T("Too few subfields (%ld), must be %ld")
#define IDS_TOOMANYSUBFIELDS    		_T("Too many subfields (%ld), must be %ld")
#define IDS_TOOFEWSUBFIELDSMIN  		_T("Too few subfields (%ld), minimum allowed is %ld")
#define IDS_TOOFEWSUBFIELDSMAX  		_T("Too many subfields (%ld), maximum allowed is %ld")
#define IDS_TOTRECORDSMAX2      		_T("Transaction Type %ls may contain at most %ld Type %ld and Type %ld records: it contains %ld")
#define IDS_TOTRECORDSMIN2      		_T("Transaction Type %ls must contain at least %ld Type %ld and Type %ld records: it only contains %ld.")
#define IDS_FLAGFIELDERROR				_T("Field %ls (%ls): %ls")
// Logfile entries
#define IDS_LOGTRANSNEW					_T("[CIWTransaction::New] Result %d")
#define IDS_LOGTRANSREAD				_T("[CIWTransaction::ReadTransactionFile] Path %s, Result %d")
#define IDS_LOGTRANSREADMEM				_T("[CIWTransaction::ReadTransactionFileMem] Result %d")
#define IDS_LOGTRANSRECORDSINFILE		_T("[CIWTransaction::GetRecords] Records in file %d")
#define IDS_LOGTRANSREADRECORDTYPE		_T("[CIWTransaction::GetRecords] Read record type %d, result %d")
#define	IDS_LOGTRANSREADRECORDFAILED	_T("[CIWTransaction::GetRecords] Read record FAILED. File %ls, type %d, result %d")
#define	IDS_LOGTRANSADDRECORD			_T("[CIWTransaction::AddRecord] Type %d, Index %d")
#define IDS_LOGTRANSREMOVEITEM			_T("[CIWTransaction::RemoveItem] (%ld, %ld, %ld, %ld, %ld)")
#define IDS_LOGTRANSGETIMAGE			_T("[CIWTransaction::GetImage] Type %d, Index %d, Result %d")
#define IDS_LOGTRANSSETIMAGE			_T("[CIWTransaction::SetImage] Type %d, Index %d, Input format %ls, Result %d")
#define IDS_LOGTRANSWRITEBINARYFAILED	_T("[CIWTransaction::WriteBinary] Write record failed. File %ls, result %d")
#define IDS_LOGTRANSWRITEMEMFAILED		_T("[CIWTransaction::WriteMem] Write record to memory failed. Result %d")
#define IDS_LOGTRANSWRITEXMLFAILED		_T("[CIWTransaction::WriteXML] WriteXML failed. File %ls, result %d")
#define IDS_LOGTRANSDEBUGSTART			_T("------------------------------- %ls")
#define IDS_LOGTRANSDEBUGEND			_T("-------------------------------")
#define IDS_LOGTRANSDEBUGCONTENTS1		_T("CONTENTS: (01) %02d items")
#define IDS_LOGTRANSDEBUGCONTENTS2		_T("CONTENTS: (%02d) %02s %02s")
#define IDS_LOGTRANSDEBUGRECORD			_T("Record %02d, Type %02d")
#define IDS_LOGTRANSDEBUGERROR			_T("error")
#define IDS_LOGFIELDGETWRITELEN			_T("[CNISTField::GetWriteLen] RecordType %d, Field %d, Len %ld")
#define IDS_LOGFIELDWRITE				_T("[CNISTField::Write] RecordType %d, Field %d")
#define	IDS_LOGRECINITNEW				_T("[CNISTRecord::InitializeNewRecord] RecordType %d")
#define IDS_LOGRECREADRECLEN			_T("[CNISTRecord::ReadLogicalRecordLen] RecordType %d, Index %d, Length %ld")
#define IDS_LOGRECREADREC				_T("[CNISTRecord::ReadRecord] RecordType %d")
#define IDS_LOGRECREADRECBIN			_T("[CNISTRecord::ReadBinaryRecord] RecordType %d")
#define IDS_LOGRECSETITEM				_T("[CNISTRecord::SetItem] (%ld, %ld, %ld): %ls")
#define IDS_LOGRECGETRECLEN				_T("[CNISTRecord::GetRecordLen] Recordtype %d, Len %ld")
#define IDS_LOGRULESETDATA				_T("[CRuleObj::SetData] Error: %ls")
#define IDS_LOGRULEDUMPOBJ1				_T("[CRuleObj::DumpObject] ==> MNU: %ls, Location: %ls, chartype %ls, len min %ld, max %ld, occ min %ld, max %ld desc(%ls) sca(%ls) date(%ls) map(%ls)")
#define IDS_LOGRULEDUMPOBJ2				_T("[CRuleObj::DumpObject] %ls, TOT's: %ls")
#define IDS_LOGRULESETTRANS				_T("[CRuleObj::SetTransactions] TOT = %ls")
#define IDS_LOGRULETESTREGEX			_T("[CRuleObj::TestRegEx] Exception thrown. %ls. Maybe an invalid mask defined.")
#define IDS_LOGVERLOADRULES				_T("[CIWVerification::LoadRules] Loc: %ls, MNU: %ls, Type: %ls, Size: %ls, Occ: %ls")
#define IDS_VERRULESUMMARY				_T("Loc: %ls, MNU: %ls, Type: %ls, Size: %ls, Occ: %ls\nLast successfully read mnemonic was %ls")
#define IDS_LOGVERREADLINE				_T("[CIWVerification::ReadLine] exception thrown")
#define IDS_LOGVERGETRULE				_T("[CIWVerification::GetRule] exception thrown")
#define IDS_LOGVERSKIPCOMMENTS			_T("[CIWVerification::SkipComments] exception thrown")
#define IDS_LOGVERGETTRANSLIST			_T("[CIWVerification::GetTransactionList] exception thrown")
#define IDS_LOGVERGETRANGETOKEN			_T("[CIWVerification::GetRangeToken] exception thrown")
#define IDS_LOGVERGETNEXTTOKEN			_T("[CIWVerification::GetNextToken] exception thrown")
#define IDS_LOGVERREADVERFILE			_T("[CIWVerification::ReadVerificationFile] Error reading verification file %s")
#define IDS_LOGVERLOADTOTDEFS			_T("[CIWVerification::LoadTOTDefinitions] %ld TOT definitions in file")
#define IDS_LOGVERLOADTOTDEFSDBG		_T("[CIWVerification::LoadTOTDefinitions] (%ls, %ls)")
#define IDS_LOGVERDBGOUTDELIM			_T("%%%%%%%%%%%%%%%%%%%%")
#define IDS_LOGVERDBGOUTMIN				_T("%ld:%ls ")
#define IDS_LOGVERDBGOUTMINMAX			_T("%ld:%ls-%ls ")
#define IDS_LOGVERDBGOUTFIELD			_T("%ls\t%ls\t%3s Len(%2ld..%2ld) Occ(%2ld..%2ld) Desc(%ls) sca(%ls) date(%ls) map(%ls) Trans %ls")
#define IDS_LOGVERVERIFYTRANS			_T("[CIWVerification::VerifyTransaction] Applying %ls\t%ls\t%3s Len(%2ld..%2ld) Occ(%2ld..%2ld) Trans %ls")
#define IDS_LOGVERVERIFYTRANSERR		_T("[CIWVerification::VerifyTransaction] Invalid Location Form Type")
#define IDS_LOGVERVERIFYFIELDCHARS		_T("[CIWVerification::VerifyFieldChars] %ls, unknown CharType: %ls")
#define IDS_LOGTRANSWRITE				_T("[CIWTransaction::Write] Path %s, Result %d")
#define IDS_LOGTRANSWRITEMEM			_T("[CIWTransaction::WriteMem] Result %d")
#define IDS_OPENEBTSLOADED				_T("--- OpenEBTS is loaded ---")
#define IDS_OPENEBTSUNLOADING			_T("--- OpenEBTS is unloading ---")

#else

// Verification file errors
#define IDS_SETTRANSFAILED				_T("SetTransaction Failed")
#define IDS_INVALIDLOCATION				_T("Invalid location: %s")
#define IDS_INVALIDMNU					_T("Invalid MNU: %s")
#define IDS_INVALIDCHARTYPE				_T("%s, invalid char type: %s")
#define IDS_INVALIDFIELDSIZE			_T("%s, invalid field size: %s")
#define IDS_INVALIDOCCURRENCES			_T("%s, invalid occurrence value: %s")
#define IDS_INVALIDDESCRIPTION			_T("%s, invalid description value: %s")
#define IDS_INVALIDLONGDESCRIPTION		_T("%s, invalid long description value: %s")
#define IDS_INVALIDSCA					_T("%s, invalid sca value: %s")
#define IDS_INVALIDDATEFORMAT			_T("%s, invalid date format value: %s")
#define IDS_INVALIDADVANCEDRULE			_T("%s, invalid advanced rule: %s")
#define IDS_INVALIDMMAP					_T("%s, invalid mmap value: %s")
#define IDS_INVALIDOMAP					_T("%s, invalid omap value: %s")
// NIST file validation errors
#define IDS_EXCEPTIONUNK        		_T("[%s] Unknown exception occurred.")
#define IDS_TOTRECORDSMAX       		_T("Transaction Type %s may contain at most %ld Type %ld records: it contains %ld")
#define IDS_TOTRECORDSMIN       		_T("Transaction Type %s must contain at least %ld Type %ld records: it only contains %ld.")
#define IDS_TOTRECORDUNSUPPORTED 		_T("Transaction Type %s may not contain Type %ld records: it contains %ld of them.")
#define IDS_MANDATORYFIELD      		_T("Mandatory field not present")
#define IDS_UNSUPPORTEDFIELD    		_T("Unsupported field present")
#define IDS_VERTOTUNK           		_T("Verification file does not contain Transaction Type %s")
#define IDS_NOTOTFIELD          		_T("Failed to find TOT field in Record 1")
#define IDS_INCORRECTITEMCOUNT  		_T("Incorrect item count (%ld), must be 1")
#define IDS_INVALIDLENGTH       		_T("Invalid length of %ld, should be %ld")
#define IDS_INVALIDLENGTHMIN    		_T("Invalid length of %ld, minimum allowed is %ld")
#define IDS_INVALIDLENGTHMAX    		_T("Invalid length of %ld, maximum allowed is %ld")
#define IDS_INVALIDTOTALLENGTH  		_T("Invalid total subfield length of %ld, should be %ld")
#define IDS_INVALIDTOTALLENGTHMIN  		_T("Invalid total subfield length of %ld, minimum allowed is %ld")
#define IDS_INVALIDTOTALLENGTHMAX  		_T("Invalid total subfield length of %ld, maximum allowed is %ld")
#define IDS_CHARINVALIDVALUE    		_T("Invalid value '%s' for CharType '%s'")
#define IDS_CHARINVALIDVALUESPECIAL 	_T("Invalid value '%s' for CharType '%s', Special Chars '%s'")
#define IDS_TOOMANYDATACHARS    		_T("Invalid value %ld for CharType '%s'")
#define IDS_INVALIDYEAR         		_T("Invalid year %ld")
#define IDS_INVALIDMONTH        		_T("Invalid month %ld")
#define IDS_INVALIDDAY          		_T("Invalid day %ld")
#define IDS_INVALIDMMAPDATA        		_T("'%s': invalid data from mandatory map")
#define IDS_TOOFEWSUBFIELDS     		_T("Too few subfields (%ld), must be %ld")
#define IDS_TOOMANYSUBFIELDS    		_T("Too many subfields (%ld), must be %ld")
#define IDS_TOOFEWSUBFIELDSMIN  		_T("Too few subfields (%ld), minimum allowed is %ld")
#define IDS_TOOFEWSUBFIELDSMAX  		_T("Too many subfields (%ld), maximum allowed is %ld")
#define IDS_TOTRECORDSMAX2      		_T("Transaction Type %s may contain at most %ld Type %ld and Type %ld records: it contains %ld")
#define IDS_TOTRECORDSMIN2      		_T("Transaction Type %s must contain at least %ld Type %ld and Type %ld records: it only contains %ld.")
#define IDS_FLAGFIELDERROR				_T("Field %s (%s): %s")
// Logfile entries
#define IDS_LOGTRANSNEW					_T("[CIWTransaction::New] Result %d")
#define IDS_LOGTRANSREAD				_T("[CIWTransaction::ReadTransactionFile] Path %s, Result %d")
#define IDS_LOGTRANSREADMEM				_T("[CIWTransaction::ReadTransactionFileMem] Result %d")
#define IDS_LOGTRANSRECORDSINFILE		_T("[CIWTransaction::GetRecords] Records in file %d")
#define IDS_LOGTRANSREADRECORDTYPE		_T("[CIWTransaction::GetRecords] Read record type %d, result %d")
#define	IDS_LOGTRANSREADRECORDFAILED 	_T("[CIWTransaction::GetRecords] Read record FAILED. File %s, type %d, result %d")
#define	IDS_LOGTRANSADDRECORD			_T("[CIWTransaction::AddRecord] Type %d, Index %d")
#define IDS_LOGTRANSREMOVEITEM			_T("[CIWTransaction::RemoveItem] (%ld, %ld, %ld, %ld, %ld)")
#define IDS_LOGTRANSGETIMAGE			_T("[CIWTransaction::GetImage] Type %d, Index %d, Result %d")
#define IDS_LOGTRANSSETIMAGE			_T("[CIWTransaction::SetImage] Type %d, Index %d, Input format %s, Result %d")
#define IDS_LOGTRANSWRITEBINARYFAILED	_T("[CIWTransaction::WriteBinary] Write record failed. File %s, result %d")
#define IDS_LOGTRANSWRITEMEMFAILED		_T("[CIWTransaction::WriteMem] Write record to memory failed. Result %d")
#define IDS_LOGTRANSWRITEXMLFAILED		_T("[CIWTransaction::WriteXML] WriteXML failed. File %s, result %d")
#define IDS_LOGTRANSDEBUGSTART			_T("------------------------------- %s")
#define IDS_LOGTRANSDEBUGEND			_T("-------------------------------")
#define IDS_LOGTRANSDEBUGCONTENTS1		_T("CONTENTS: (01) %02d items")
#define IDS_LOGTRANSDEBUGCONTENTS2		_T("CONTENTS: (%02d) %02s %02s")
#define IDS_LOGTRANSDEBUGRECORD			_T("Record %02d, Type %02d")
#define IDS_LOGTRANSDEBUGERROR			_T("error")
#define IDS_LOGFIELDGETWRITELEN			_T("[CNISTField::GetWriteLen] RecordType %d, Field %d, Len %ld")
#define IDS_LOGFIELDWRITE				_T("[CNISTField::Write] RecordType %d, Field %d")
#define	IDS_LOGRECINITNEW				_T("[CNISTRecord::InitializeNewRecord] RecordType %d")
#define IDS_LOGRECREADRECLEN			_T("[CNISTRecord::ReadLogicalRecordLen] RecordType %d, Index %d, Length %ld")
#define IDS_LOGRECREADREC				_T("[CNISTRecord::ReadRecord] RecordType %d")
#define IDS_LOGRECREADRECBIN			_T("[CNISTRecord::ReadBinaryRecord] RecordType %d")
#define IDS_LOGRECSETITEM				_T("[CNISTRecord::SetItem] (%ld, %ld, %ld): %s")
#define IDS_LOGRECGETRECLEN				_T("[CNISTRecord::GetRecordLen] Recordtype %d, Len %ld")
#define IDS_LOGRULESETDATA				_T("[CRuleObj::SetData] Error: %s")
#define IDS_LOGRULEDUMPOBJ1				_T("[CRuleObj::DumpObject] ==> MNU: %s, Location: %s, chartype %s, len min %ld, max %ld, occ min %ld, max %ld desc(%s) sca(%s) date(%s) map(%s)")
#define IDS_LOGRULEDUMPOBJ2				_T("[CRuleObj::DumpObject] %s, TOT's: %s")
#define IDS_LOGRULESETTRANS				_T("[CRuleObj::SetTransactions] TOT = %s")
#define IDS_LOGRULETESTREGEX			_T("[CRuleObj::TestRegEx] Exception thrown. %s. Maybe an invalid mask defined.")
#define IDS_LOGVERLOADRULES				_T("[CIWVerification::LoadRules] Loc: %s, MNU: %s, Type: %s, Size: %s, Occ: %s")
#define IDS_VERRULESUMMARY				_T("Loc: %s, MNU: %s, Type: %s, Size: %s, Occ: %s\nLast successfully read mnemonic was %s")
#define IDS_LOGVERREADLINE				_T("[CIWVerification::ReadLine] exception thrown")
#define IDS_LOGVERGETRULE				_T("[CIWVerification::GetRule] exception thrown")
#define IDS_LOGVERSKIPCOMMENTS			_T("[CIWVerification::SkipComments] exception thrown")
#define IDS_LOGVERGETTRANSLIST			_T("[CIWVerification::GetTransactionList] exception thrown")
#define IDS_LOGVERGETRANGETOKEN			_T("[CIWVerification::GetRangeToken] exception thrown")
#define IDS_LOGVERGETNEXTTOKEN			_T("[CIWVerification::GetNextToken] exception thrown")
#define IDS_LOGVERREADVERFILE			_T("[CIWVerification::ReadVerificationFile] Error reading verification file %s")
#define IDS_LOGVERLOADTOTDEFS			_T("[CIWVerification::LoadTOTDefinitions] %ld TOT definitions in file")
#define IDS_LOGVERLOADTOTDEFSDBG		_T("[CIWVerification::LoadTOTDefinitions] (%s, %s)")
#define IDS_LOGVERDBGOUTDELIM			_T("%%%%%%%%%%%%%%%%%%%%")
#define IDS_LOGVERDBGOUTMIN				_T("%ld:%s ")
#define IDS_LOGVERDBGOUTMINMAX			_T("%ld:%s-%s ")
#define IDS_LOGVERDBGOUTFIELD			_T("%s\t%s\t%3s Len(%2ld..%2ld) Occ(%2ld..%2ld) Desc(%s) sca(%s) date(%s) map(%s) Trans %s")
#define IDS_LOGVERVERIFYTRANS			_T("[CIWVerification::VerifyTransaction] Applying %s\t%s\t%3s Len(%2ld..%2ld) Occ(%2ld..%2ld) Trans %s")
#define IDS_LOGVERVERIFYTRANSERR		_T("[CIWVerification::VerifyTransaction] Invalid Location Form Type")
#define IDS_LOGVERVERIFYFIELDCHARS		_T("[CIWVerification::VerifyFieldChars] %s, unknown CharType: %s")
#define IDS_LOGTRANSWRITE				_T("[CIWTransaction::Write] Path %s, Result %d")
#define IDS_LOGTRANSWRITEMEM			_T("[CIWTransaction::WriteMem] Result %d")
#define IDS_OPENEBTSLOADED				_T("--- OpenEBTS is loaded ---")
#define IDS_OPENEBTSUNLOADING			_T("--- OpenEBTS is unloading ---")

#endif

#else

#ifdef UNICODE

// Verification file errors
#define IDS_SETTRANSFAILED				_T("SetTransaction ha fallado")
#define IDS_INVALIDLOCATION				_T("Ubicación inválida: %ls")
#define IDS_INVALIDMNU					_T("MNU erroneo: %ls")
#define IDS_INVALIDCHARTYPE				_T("%ls, tipo de carácter inválido: %ls")
#define IDS_INVALIDFIELDSIZE			_T("%ls, longitud de campo inválida: %ls")
#define IDS_INVALIDOCCURRENCES			_T("%ls, valor de ocurencia inválido: %ls")
#define IDS_INVALIDDESCRIPTION			_T("%ls, valor de descripción corta inválido: %ls")
#define IDS_INVALIDLONGDESCRIPTION		_T("%ls, valor de descripción larga inválido: %ls")
#define IDS_INVALIDSCA					_T("%ls, valor sca inválido: %ls")
#define IDS_INVALIDDATEFORMAT			_T("%ls, valor de formato de fecha inválido: %ls")
#define IDS_INVALIDADVANCEDRULE			_T("%ls, regla avanzada inválida: %ls")
#define IDS_INVALIDMMAP					_T("%ls, valor mmap inválido: %ls")
#define IDS_INVALIDOMAP					_T("%ls, valor omap inválido: %ls")
// NIST file validation errors
#define IDS_EXCEPTIONUNK        		_T("[%ls] Excepción desconocida.")
#define IDS_TOTRECORDSMAX       		_T("El tipo de transacción %ls debería tener un máximo de %ld grabaciones de tipo %ld: contiene %ld")
#define IDS_TOTRECORDSMIN       		_T("El tipo de transacción %ls debe tener un mínimo de %ld grabaciones de tipo %ld: sólo tiene %ld.")
#define IDS_TOTRECORDUNSUPPORTED 		_T("El tipo de transacción %ls no debería tener grabaciones de tipo %ld: tiene %ld de ellas.")
#define IDS_MANDATORYFIELD      		_T("Un campo obligatorio esta faltando")
#define IDS_UNSUPPORTEDFIELD    		_T("Un campo presente no esta soportado")
#define IDS_VERTOTUNK           		_T("El archivo VER no toma en cuenta las transacciones de tipo %ls")
#define IDS_NOTOTFIELD          		_T("No se ha logrado encontrar el campo TOT en la grabación 1")
#define IDS_INCORRECTITEMCOUNT  		_T("Número incorrecto de (%ld), debe ser 1")
#define IDS_INVALIDLENGTH       		_T("Longitud de %ld inválida, debería ser %ld")
#define IDS_INVALIDLENGTHMIN    		_T("Longitud de %ld inválida, el mínimo permitido es %ld")
#define IDS_INVALIDLENGTHMAX    		_T("Longitud de %ld inválida, el máximo permitido es %ld")
#define IDS_INVALIDTOTALLENGTH  		_T("Longitud total de subcampo %ld inválida, debería ser %ld")
#define IDS_INVALIDTOTALLENGTHMIN  		_T("Longitud total de subcampo %ld inválida, el mínimo permitido es %ld")
#define IDS_INVALIDTOTALLENGTHMAX		_T("Longitud total de subcampo %ld inválida, el máximo permitido es %ld")
#define IDS_CHARINVALIDVALUE    		_T("Valor '%ls' inválido para el tipo '%ls'")
#define IDS_CHARINVALIDVALUESPECIAL		_T("Valor '%ls' inválido para el tipo '%ls, caracteres especiales '%ls'")
#define IDS_TOOMANYDATACHARS    		_T("Valor '%ld' inválido para el tipo '%ls'")
#define IDS_INVALIDYEAR         		_T("Año %ld inválido")
#define IDS_INVALIDMONTH        		_T("Mes %ld inválido")
#define IDS_INVALIDDAY          		_T("Día %ld inválido")
#define IDS_INVALIDMMAPDATA				_T("'%ls': valor inválido para el map obligatorio")
#define IDS_TOOFEWSUBFIELDS     		_T("Campos (%ld) insuficientes, deben ser %ld")
#define IDS_TOOMANYSUBFIELDS    		_T("Demasiados campos (%ld), deben ser %ld")
#define IDS_TOOFEWSUBFIELDSMIN  		_T("Campos (%ld) insuficientes, el mínimo aceptable es %ld")
#define IDS_TOOFEWSUBFIELDSMAX  		_T("Demasiados campos (%ld), el máximo aceptable es %ld")
#define IDS_TOTRECORDSMAX2      		_T("La transacción de tipo %ls debería contener un máximo de %ld registros de tipo %ld o %ld: contiene %ld")
#define IDS_TOTRECORDSMIN2      		_T("La transacción de tipo %ls debería contener un mínimo de %ld registros de tipo %ld o %ld: solamente tiene %ld.")
#define IDS_FLAGFIELDERROR				_T("Campo %ls (%ls): %ls")
// Logfile entries
#define IDS_LOGTRANSNEW					_T("[CIWTransaction::New] Resultado %d")
#define IDS_LOGTRANSREAD				_T("[CIWTransaction::ReadTransactionFile] Ruta %s, Resultado %d")
#define IDS_LOGTRANSREADMEM				_T("[CIWTransaction::ReadTransactionFileMem] Resultado %d")
#define IDS_LOGTRANSRECORDSINFILE		_T("[CIWTransaction::GetRecords] Registros en el archivo %d")
#define IDS_LOGTRANSREADRECORDTYPE		_T("[CIWTransaction::GetRecords] Lectura de registro de tipo %d, resultado %d")
#define	IDS_LOGTRANSREADRECORDFAILED	_T("[CIWTransaction::GetRecords] Error en lectura de registro. Archivo %ls, tipo %d, resultado %d")
#define	IDS_LOGTRANSADDRECORD			_T("[CIWTransaction::AddRecord] Tipo %d, Indice %d")
#define IDS_LOGTRANSREMOVEITEM			_T("[CIWTransaction::RemoveItem] (%ld, %ld, %ld, %ld, %ld)")
#define IDS_LOGTRANSGETIMAGE			_T("[CIWTransaction::GetImage] Tipo %d, Indice %d, Resultado %d")
#define IDS_LOGTRANSSETIMAGE			_T("[CIWTransaction::SetImage] Tipo %d, Indice %d, Formato de entrada %ls, Resultado %d")
#define IDS_LOGTRANSWRITEBINARYFAILED	_T("[CIWTransaction::WriteBinary] Error en escritura de registro. Archivo %ls, resultado %d")
#define IDS_LOGTRANSWRITEMEMFAILED		_T("[CIWTransaction::WriteMem] Error de escritura de registro en memoria. Resultado %d")
#define IDS_LOGTRANSWRITEXMLFAILED		_T("[CIWTransaction::WriteXML] Error en escritura XML. Archivo %ls, resultado %d")
#define IDS_LOGTRANSDEBUGSTART			_T("------------------------------- %ls")
#define IDS_LOGTRANSDEBUGEND			_T("-------------------------------")
#define IDS_LOGTRANSDEBUGCONTENTS1		_T("CONTENIDO: (01) %02d elementos")
#define IDS_LOGTRANSDEBUGCONTENTS2		_T("CONTENIDO: (%02d) %02s %02s")
#define IDS_LOGTRANSDEBUGRECORD			_T("Registro %02d, Tipo %02d")
#define IDS_LOGTRANSDEBUGERROR			_T("error")
#define IDS_LOGFIELDGETWRITELEN			_T("[CNISTField::GetWriteLen] Tipo de registro %d, Campo %d, Longitud %ld")
#define IDS_LOGFIELDWRITE				_T("[CNISTField::Write] Tipo de registro %d, Campo %d")
#define	IDS_LOGRECINITNEW				_T("[CNISTRecord::InitializeNewRecord] Tipo de registro %d")
#define IDS_LOGRECREADRECLEN			_T("[CNISTRecord::ReadLogicalRecordLen] Tipo de registro %d, Indice %d, Longitud %ld")
#define IDS_LOGRECREADREC				_T("[CNISTRecord::ReadRecord] Tipo de registro %d")
#define IDS_LOGRECREADRECBIN			_T("[CNISTRecord::ReadBinaryRecord] Tipo de registro %d")
#define IDS_LOGRECSETITEM				_T("[CNISTRecord::SetItem] (%ld, %ld, %ld): %ls")
#define IDS_LOGRECGETRECLEN				_T("[CNISTRecord::GetRecordLen] Tipo de registro %d, Longitud %ld")
#define IDS_LOGRULESETDATA				_T("[CRuleObj::SetData] Error: %ls")
#define IDS_LOGRULEDUMPOBJ1				_T("[CRuleObj::DumpObject] ==> MNU: %ls, Ubicación: %ls, Tipo de carácter %ls, Longitud min %ld, max %ld, occ min %ld, max %ld desc(%ls) sca(%ls) fecha(%ls) mapa(%ls)")
#define IDS_LOGRULEDUMPOBJ2				_T("[CRuleObj::DumpObject] %ls, TOT's: %ls")
#define IDS_LOGRULESETTRANS				_T("[CRuleObj::SetTransactions] TOT = %ls")
#define IDS_LOGRULETESTREGEX			_T("[CRuleObj::TestRegEx] Excepción. %ls. Posible mascara inválida.")
#define IDS_LOGVERLOADRULES				_T("[CIWVerification::LoadRules] Ubic: %ls, MNU: %ls, Tipo: %ls, Tamaño: %ls, Occ: %ls")
#define IDS_VERRULESUMMARY				_T("Ubic: %ls, MNU: %ls, Tipo: %ls, Tamaño: %ls, Occ: %ls\nLectura exitosa anterior: %ls")
#define IDS_LOGVERREADLINE				_T("[CIWVerification::ReadLine] Excepción")
#define IDS_LOGVERGETRULE				_T("[CIWVerification::GetRule] Excepción")
#define IDS_LOGVERSKIPCOMMENTS			_T("[CIWVerification::SkipComments] Excepción")
#define IDS_LOGVERGETTRANSLIST			_T("[CIWVerification::GetTransactionList] Excepción")
#define IDS_LOGVERGETRANGETOKEN			_T("[CIWVerification::GetRangeToken] Excepción")
#define IDS_LOGVERGETNEXTTOKEN			_T("[CIWVerification::GetNextToken] Excepción")
#define IDS_LOGVERREADVERFILE			_T("[CIWVerification::ReadVerificationFile] Error en lectura de archivo VER %s")
#define IDS_LOGVERLOADTOTDEFS			_T("[CIWVerification::LoadTOTDefinitions] %ld definiciones de TOT en el archivo")
#define IDS_LOGVERLOADTOTDEFSDBG		_T("[CIWVerification::LoadTOTDefinitions] (%ls, %ls)")
#define IDS_LOGVERDBGOUTDELIM			_T("%%%%%%%%%%%%%%%%%%%%")
#define IDS_LOGVERDBGOUTMIN				_T("%ld:%ls ")
#define IDS_LOGVERDBGOUTMINMAX			_T("%ld:%ls-%ls ")
#define IDS_LOGVERDBGOUTFIELD			_T("%ls\t%ls\t%3s Len(%2ld..%2ld) Occ(%2ld..%2ld) Desc(%ls) sca(%ls) date(%ls) map(%ls) Trans %ls")
#define IDS_LOGVERVERIFYTRANS			_T("[CIWVerification::VerifyTransaction] Aplicando %ls\t%ls\t%3s Len(%2ld..%2ld) Occ(%2ld..%2ld) Trans %ls")
#define IDS_LOGVERVERIFYTRANSERR		_T("[CIWVerification::VerifyTransaction] Tipo de formato de ubicación inválido")
#define IDS_LOGVERVERIFYFIELDCHARS		_T("[CIWVerification::VerifyFieldChars] %ls, tipo de carácter desconocido: %ls")
#define IDS_LOGTRANSWRITE				_T("[CIWTransaction::Write] Ruta %s, Resultado %d")
#define IDS_LOGTRANSWRITEMEM			_T("[CIWTransaction::WriteMem] Resultado %d")
#define IDS_OPENEBTSLOADED				_T("--- OpenEBTS se esta cargando ---")
#define IDS_OPENEBTSUNLOADING			_T("--- OpenEBTS se esta descargando ---")

#else

// Verification file errors
#define IDS_SETTRANSFAILED				_T("SetTransaction ha fallado")
#define IDS_INVALIDLOCATION				_T("Ubicación inválida: %s")
#define IDS_INVALIDMNU					_T("MNU inválido: %s")
#define IDS_INVALIDCHARTYPE				_T("%s, tipo de carácter inválido: %s")
#define IDS_INVALIDFIELDSIZE			_T("%s, tamaño de campo inválido: %s")
#define IDS_INVALIDOCCURRENCES			_T("%s, valor de ocurencia inválido: %s")
#define IDS_INVALIDDESCRIPTION			_T("%s, valor de descripción inválido: %s")
#define IDS_INVALIDLONGDESCRIPTION		_T("%s, valor de descripción larga inválido: %s")
#define IDS_INVALIDSCA					_T("%s, valor sca inválido: %s")
#define IDS_INVALIDDATEFORMAT			_T("%s, valor de formato de fecha inválido: %s")
#define IDS_INVALIDADVANCEDRULE			_T("%s, regla avanzada inválida: %s")
#define IDS_INVALIDMMAP					_T("%s, valor mmap inválido: %s")
#define IDS_INVALIDOMAP					_T("%s, valor omap inválido: %s")
// NIST file validation errors
#define IDS_EXCEPTIONUNK        		_T("[%s] excepción desconocida.")
#define IDS_TOTRECORDSMAX       		_T("El tipo de transacción %s debería tener un máximo de %ld registros de tipo %ld: tiene %ld")
#define IDS_TOTRECORDSMIN       		_T("El tipo de transacción %s debe tener por lo menos %ld registros de tipo %ld: contiene solamente %ld.")
#define IDS_TOTRECORDUNSUPPORTED 		_T("El tipo de transacción %s no debería tener registros de tipo %ld: tiene %ld de este tipo.")
#define IDS_MANDATORYFIELD      		_T("Un campo obligatorio esta faltando")
#define IDS_UNSUPPORTEDFIELD    		_T("Presencia de campo no soportado")
#define IDS_VERTOTUNK           		_T("El archivo VER no contiene la transacción %s")
#define IDS_NOTOTFIELD          		_T("No se encuentra el campo TOT en el registro 1")
#define IDS_INCORRECTITEMCOUNT  		_T("Conteo incorrecto de objeto (%ld), debe ser 1")
#define IDS_INVALIDLENGTH       		_T("Longitud incorrecta de %ld, debería ser %ld")
#define IDS_INVALIDLENGTHMIN    		_T("Longitud incorrecta de %ld, mínimo necesario es %ld")
#define IDS_INVALIDLENGTHMAX    		_T("Longitud incorrecta de %ld, máximo aceptable %ld")
#define IDS_INVALIDTOTALLENGTH  		_T("Longitud incorrecta del subcampo %ld, debería ser %ld")
#define IDS_INVALIDTOTALLENGTHMIN  		_T("Longitud incorrecta del subcampo %ld, mínimo necesario %ld")
#define IDS_INVALIDTOTALLENGTHMAX  		_T("Longitud incorrecta del subcampo %ld, máximo aceptable %ld")
#define IDS_CHARINVALIDVALUE    		_T("Valor inválido '%s' para tipo de carácter '%s'")
#define IDS_CHARINVALIDVALUESPECIAL 	_T("Valor inválido '%s' para tipo de carácter '%s', carácteres especiales '%s'")
#define IDS_TOOMANYDATACHARS    		_T("Valor inválido %ld para tipo de carácter '%s'")
#define IDS_INVALIDYEAR         		_T("Año inválido %ld")
#define IDS_INVALIDMONTH        		_T("Mes inválido %ld")
#define IDS_INVALIDDAY          		_T("Día inválido %ld")
#define IDS_INVALIDMMAPDATA        		_T("'%s': dato inválido del map obligatorio")
#define IDS_TOOFEWSUBFIELDS     		_T("Subcampos insuficicentes (%ld), debe ser %ld")
#define IDS_TOOMANYSUBFIELDS    		_T("Demasiados subcampos (%ld), debe ser %ld")
#define IDS_TOOFEWSUBFIELDSMIN  		_T("Subcampos insuficicentes (%ld), mínimo de %ld")
#define IDS_TOOFEWSUBFIELDSMAX  		_T("Demasiados subcampos (%ld), máximo permitido es %ld")
#define IDS_TOTRECORDSMAX2      		_T("El tipo de transacción %s debería contener un máximo de %ld registros de tipo %ld y %ld: tiene %ld")
#define IDS_TOTRECORDSMIN2      		_T("El tipo de transacción %s debe tener por lo menos %ld registros de tipo %ld y %ld: Solamente contiene %ld.")
#define IDS_FLAGFIELDERROR				_T("Field %s (%s): %s")
// Logfile entries
#define IDS_LOGTRANSNEW					_T("[CIWTransaction::New] Resultado %d")
#define IDS_LOGTRANSREAD				_T("[CIWTransaction::ReadTransactionFile] Ruta %s, Resultado %d")
#define IDS_LOGTRANSREADMEM				_T("[CIWTransaction::ReadTransactionFileMem] Resultado %d")
#define IDS_LOGTRANSRECORDSINFILE		_T("[CIWTransaction::GetRecords] Registros en archivo %d")
#define IDS_LOGTRANSREADRECORDTYPE		_T("[CIWTransaction::GetRecords] Lectura de registro de tipo %d, resultado %d")
#define	IDS_LOGTRANSREADRECORDFAILED 	_T("[CIWTransaction::GetRecords] Falla en lectura de registro. Archivo %s, tipo %d, resultado %d")
#define	IDS_LOGTRANSADDRECORD			_T("[CIWTransaction::AddRecord] Tipo %d, Índice %d")
#define IDS_LOGTRANSREMOVEITEM			_T("[CIWTransaction::RemoveItem] (%ld, %ld, %ld, %ld, %ld)")
#define IDS_LOGTRANSGETIMAGE			_T("[CIWTransaction::GetImage] Tipo %d, Índice %d, Resultado %d")
#define IDS_LOGTRANSSETIMAGE			_T("[CIWTransaction::SetImage] Tipo %d, Índice %d, Formato entrada %s, Resultado %d")
#define IDS_LOGTRANSWRITEBINARYFAILED	_T("[CIWTransaction::WriteBinary] Falla en escritura de registro. Archivo %s, resultado %d")
#define IDS_LOGTRANSWRITEMEMFAILED		_T("[CIWTransaction::WriteMem] Falla en escritura de registro en memoria. Resultado %d")
#define IDS_LOGTRANSWRITEXMLFAILED		_T("[CIWTransaction::WriteXML] Falla en escritura XML. Archivo %s, resultado %d")
#define IDS_LOGTRANSDEBUGSTART			_T("------------------------------- %s")
#define IDS_LOGTRANSDEBUGEND			_T("-------------------------------")
#define IDS_LOGTRANSDEBUGCONTENTS1		_T("CONTENIDOS: (01) %02d elementos")
#define IDS_LOGTRANSDEBUGCONTENTS2		_T("CONTENIDOS: (%02d) %02s %02s")
#define IDS_LOGTRANSDEBUGRECORD			_T("Registro %02d, Tipo %02d")
#define IDS_LOGTRANSDEBUGERROR			_T("error")
#define IDS_LOGFIELDGETWRITELEN			_T("[CNISTField::GetWriteLen] Tipo de registro %d, Campo %d, Longitud %ld")
#define IDS_LOGFIELDWRITE				_T("[CNISTField::Write] Tipo de registro %d, Campo %d")
#define	IDS_LOGRECINITNEW				_T("[CNISTRecord::InitializeNewRecord] Tipo de registro %d")
#define IDS_LOGRECREADRECLEN			_T("[CNISTRecord::ReadLogicalRecordLen] Tipo de registro %d, Índice %d, Longitud %ld")
#define IDS_LOGRECREADREC				_T("[CNISTRecord::ReadRecord] Tipo de registro %d")
#define IDS_LOGRECREADRECBIN			_T("[CNISTRecord::ReadBinaryRecord] Tipo de registro %d")
#define IDS_LOGRECSETITEM				_T("[CNISTRecord::SetItem] (%ld, %ld, %ld): %s")
#define IDS_LOGRECGETRECLEN				_T("[CNISTRecord::GetRecordLen] Tipo de registro %d, Len %ld")
#define IDS_LOGRULESETDATA				_T("[CRuleObj::SetData] Error: %s")
#define IDS_LOGRULEDUMPOBJ1				_T("[CRuleObj::DumpObject] ==> MNU: %s, Ubicación: %s, tipo de carácter %s, len min %ld, max %ld, occ min %ld, max %ld desc(%s) sca(%s) date(%s) map(%s)")
#define IDS_LOGRULEDUMPOBJ2				_T("[CRuleObj::DumpObject] %s, TOT's: %s")
#define IDS_LOGRULESETTRANS				_T("[CRuleObj::SetTransactions] TOT = %s")
#define IDS_LOGRULETESTREGEX			_T("[CRuleObj::TestRegEx] Exception thrown. %s. Posible mascara inválida.")
#define IDS_LOGVERLOADRULES				_T("[CIWVerification::LoadRules] Loc: %s, MNU: %s, Type: %s, Size: %s, Occ: %s")
#define IDS_VERRULESUMMARY				_T("Ubic: %s, MNU: %s, Type: %s, Size: %s, Occ: %s\nEl último mnemonico leido con éxito fue %s")
#define IDS_LOGVERREADLINE				_T("[CIWVerification::ReadLine] excepción")
#define IDS_LOGVERGETRULE				_T("[CIWVerification::GetRule] excepción")
#define IDS_LOGVERSKIPCOMMENTS			_T("[CIWVerification::SkipComments] excepción")
#define IDS_LOGVERGETTRANSLIST			_T("[CIWVerification::GetTransactionList] excepción")
#define IDS_LOGVERGETRANGETOKEN			_T("[CIWVerification::GetRangeToken] excepción")
#define IDS_LOGVERGETNEXTTOKEN			_T("[CIWVerification::GetNextToken] excepción")
#define IDS_LOGVERREADVERFILE			_T("[CIWVerification::ReadVerificationFile] Error de lectura de archivo VER %s")
#define IDS_LOGVERLOADTOTDEFS			_T("[CIWVerification::LoadTOTDefinitions] %ld definiciones de TOT en archivo")
#define IDS_LOGVERLOADTOTDEFSDBG		_T("[CIWVerification::LoadTOTDefinitions] (%s, %s)")
#define IDS_LOGVERDBGOUTDELIM			_T("%%%%%%%%%%%%%%%%%%%%")
#define IDS_LOGVERDBGOUTMIN				_T("%ld:%s ")
#define IDS_LOGVERDBGOUTMINMAX			_T("%ld:%s-%s ")
#define IDS_LOGVERDBGOUTFIELD			_T("%s\t%s\t%3s Len(%2ld..%2ld) Occ(%2ld..%2ld) Desc(%s) sca(%s) date(%s) map(%s) Trans %s")
#define IDS_LOGVERVERIFYTRANS			_T("[CIWVerification::VerifyTransaction] Aplicando %s\t%s\t%3s Len(%2ld..%2ld) Occ(%2ld..%2ld) Trans %s")
#define IDS_LOGVERVERIFYTRANSERR		_T("[CIWVerification::VerifyTransaction] Tipo de formato de ubicación inválido")
#define IDS_LOGVERVERIFYFIELDCHARS		_T("[CIWVerification::VerifyFieldChars] %s, Tipo de carácter desconocido: %s")
#define IDS_LOGTRANSWRITE				_T("[CIWTransaction::Write] Ruta %s, Resultado %d")
#define IDS_LOGTRANSWRITEMEM			_T("[CIWTransaction::WriteMem] Resultado %d")
#define IDS_OPENEBTSLOADED				_T("--- OpenEBTS se esta cargando ---")
#define IDS_OPENEBTSUNLOADING			_T("--- OpenEBTS se esta descargando ---")

#endif

#endif



